/*

This file contains HTML code for app of WiFi Message Board

*/

const String page PROGMEM = "<head>"
            " <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            " <link href='https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap' rel='stylesheet'>"
            " <style>"
            " body{"
            " background-color:white;"
            " font-family: 'Roboto', sans-serif;" 
            "}"
            "p, div {font-size: 14px;color: #888;margin-bottom: 10px;}\n"
            "div {margin: 30px;}"
            ".checkdays {display: block; padding: 10px;}"
            ".button {display: block;background-color: #3498db;border: none;color: white;padding: 13px 30px;text-decoration: none;font-size: 25px;margin: 0px auto 35px;cursor: pointer;border-radius: 4px;}\n"
            ".button:active {background-color: #2980b9;}\n"
            ".days {padding:10px;border: 1px solid #000;}\n"
            "</style>"
            " </head>"
            " <body>"
            " <h1>The clock</h1>"
            "<hr />"
            "<div class='form'>"
            " <form action='/setAlarm' method='POST'>\r\n"
            "%ALARM_SWITCH%"
            " <div><label for='alarmTime'>Alarm time:</label> <input type='time' name='alarmTime' id='alarmTime' value='%ALARM%'>""</div>\r\n" 
            " <div>"
            " <div class='days' ><label for='d1'>sun</label><input class='checkdays' type='checkbox' name = 'd1' %D1% /></div>\r\n"
            " <div class='days' ><label for='d2'>mon</label><input class='checkdays' type='checkbox' name = 'd2' %D2% /></div>\r\n"
            " <div class='days' ><label for='d3'>tue</label><input class='checkdays' type='checkbox' name = 'd3' %D3% /></div>\r\n"
            " <div class='days' ><label for='d4'>wed</label><input class='checkdays' type='checkbox' name = 'd4' %D4% /></div>\r\n"
            " <div class='days' ><label for='d5'>thu</label><input class='checkdays' type='checkbox' name = 'd5' %D5% /></div>\r\n"
            " <div class='days' ><label for='d6'>fri</label><input class='checkdays' type='checkbox' name = 'd6' %D6% /></div>\r\n"
            " <div class='days' ><label for='d7'>sat</label><input class='checkdays' type='checkbox' name = 'd7' %D7% /></div>\r\n"
            "</div>"
            "<div>"
            "<label for='brightness'>Brightness (between 1 and 9):</label>"
            "<input type='number' id='brightness' name='brightness' min='1' max='9' value = '%BRIGHTNESS%'>"
            "</div>"
            " <div><button class='button' type='submit' id='send'>Save </button></div>\r\n "
            " </form> \r\n"
            "</div>"
            "</body>";
